# node api endpoint
apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: testnet
spec:
  ports:
    - protocol: TCP
      name: api
      port: 1317
      targetPort: 1317
    - protocol: TCP
      name: rpc
      port: 26657
      targetPort: 26657
  type: ExternalName
  externalName: testnet-node.humans.zone
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node
  namespace: testnet
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - rpc-testnet.humans.zone
        - api-testnet.humans.zone
      secretName: node-humans-zone
  rules:
    - host: api-testnet.humans.zone
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node
                port:
                  number: 1317
    - host: api-rpc.humans.zone
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node
                port:
                  number: 26657
